In [322]:
# pipenv install pandas numpy matplotlib seaborn plotly nbformat scipy scikit-learn ipykernel
# Importar as bibliotecas

# EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from scipy.stats import chi2_contingency

sns.set_style('whitegrid')

# Machine Learning
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### Carregar os Dados

In [323]:
# Carregar os dados
df_leads = pd.read_csv('./datasets/leads.csv')

In [324]:
# Mostrar as primeiras linhas
df_leads.head(10)

Prospect ID  Lead Number              Lead Origin  \
0  7927b2df-8bba-4d29-b9a2-b6e0beafe620       660737                      API   
1  2a272436-5132-4136-86fa-dcc88c88f482       660728                      API   
2  8cc8c611-a219-4f35-ad23-fdfd2656bd8a       660727  Landing Page Submission   
3  0cc2df48-7cf4-4e39-9de9-19797f9b38cc       660719  Landing Page Submission   
4  3256f628-e534-4826-9d63-4a8b88782852       660681  Landing Page Submission   
5  2058ef08-2858-443e-a01f-a9237db2f5ce       660680                      API   
6  9fae7df4-169d-489b-afe4-0f3d752542ed       660673  Landing Page Submission   
7  20ef72a2-fb3b-45e0-924e-551c5fa59095       660664                      API   
8  cfa0128c-a0da-4656-9d47-0aa4e67bf690       660624  Landing Page Submission   
9  af465dfc-7204-4130-9e05-33231863c4b5       660616                      API   

      Lead Source Do Not Email Do Not Call  Converted  TotalVisits  \
0      Olark Chat           No          No          0          0.0   
1  Organic Search           No          No          0          5.0   
2  Direct Traffic           No          No          1          2.0   
3  Direct Traffic           No          No          0          1.0   
4          Google           No          No          1          2.0   
5      Olark Chat           No          No          0          0.0   
6          Google           No          No          1          2.0   
7      Olark Chat           No          No          0          0.0   
8  Direct Traffic           No          No          0          2.0   
9          Google           No          No          0          4.0   

   Total Time Spent on Website  Page Views Per Visit  ...  \
0                            0                   0.0  ...   
1                          674                   2.5  ...   
2                         1532                   2.0  ...   
3                          305                   1.0  ...   
4                         1428                   1.0  ...   
5                            0                   0.0  ...   
6                         1640                   2.0  ...   
7                            0                   0.0  ...   
8                           71                   2.0  ...   
9                           58                   4.0  ...   

  Get updates on DM Content    Lead Profile               City  \
0                        No          Select             Select   
1                        No          Select             Select   
2                        No  Potential Lead             Mumbai   
3                        No          Select             Mumbai   
4                        No          Select             Mumbai   
5                        No             NaN                NaN   
6                        No  Potential Lead             Mumbai   
7                        No             NaN                NaN   
8                        No             NaN  Thane & Outskirts   
9                        No             NaN             Mumbai   

  Asymmetrique Activity Index Asymmetrique Profile Index  \
0                   02.Medium                  02.Medium   
1                   02.Medium                  02.Medium   
2                   02.Medium                    01.High   
3                   02.Medium                    01.High   
4                   02.Medium                    01.High   
5                     01.High                  02.Medium   
6                   02.Medium                    01.High   
7                   02.Medium                  02.Medium   
8                   02.Medium                  02.Medium   
9                   02.Medium                  02.Medium   

  Asymmetrique Activity Score Asymmetrique Profile Score  \
0                        15.0                       15.0   
1                        15.0                       15.0   
2                        14.0                       20.0   
3                        13.0                       17.0   
4    

In [325]:
# Mostrar as ultimas linhas
df_leads.tail(10)

Prospect ID  Lead Number  \
9230  d11c15b7-8056-45a6-8954-771c0d0495fe       579701   
9231  4aeae36b-2b57-494f-bdab-dd58844286b4       579697   
9232  2d0109e9-dfb2-4664-83de-c2ea75ec7516       579642   
9233  3f715465-2546-47cd-afa8-8b8dc63b8b43       579622   
9234  c0b25922-511f-4c56-852e-ced210a45447       579615   
9235  19d6451e-fcd6-407c-b83b-48e1af805ea9       579564   
9236  82a7005b-7196-4d56-95ce-a79f937a158d       579546   
9237  aac550fe-a586-452d-8d3c-f1b62c94e02c       579545   
9238  5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9       579538   
9239  571b5c8e-a5b2-4d57-8574-f2ffb06fdeff       579533   

                  Lead Origin     Lead Source Do Not Email Do Not Call  \
9230  Landing Page Submission          Google           No          No   
9231  Landing Page Submission          Google           No          No   
9232  Landing Page Submission  Direct Traffic           No          No   
9233                      API  Direct Traffic           No          No   
9234  Landing Page Submission  Direct Traffic           No          No   
9235  Landing Page Submission  Direct Traffic          Yes          No   
9236  Landing Page Submission  Direct Traffic           No          No   
9237  Landing Page Submission  Direct Traffic          Yes          No   
9238  Landing Page Submission          Google           No          No   
9239  Landing Page Submission  Direct Traffic           No          No   

      Converted  TotalVisits  Total Time Spent on Website  \
9230          0          2.0                          870   
9231          1          8.0                         1016   
9232          0          2.0                         1770   
9233          1         13.0                         1409   
9234          1          5.0                          210   
9235          1          8.0                         1845   
9236          0          2.0                          238   
9237          0          2.0                          199   
9238          1          3.0                          499   
9239          1          6.0                         1279   

      Page Views Per Visit  ... Get updates on DM Content    Lead Profile  \
9230                  2.00  ...                        No  Potential Lead   
9231                  4.00  ...                        No  Potential Lead   
9232                  2.00  ...                        No  Potential Lead   
9233                  2.60  ...                        No          Select   
9234                  2.50  ...                        No  Potential Lead   
9235                  2.67  ...                        No  Potential Lead   
9236                  2.00  ...                        No  Potential Lead   
9237                  2.00  ...                        No  Potential Lead   
9238                  3.00  ...                        No             NaN   
9239                  3.00  ...                        No  Potential Lead   

                    City Asymmetrique Activity Index  \
9230              Mumbai                   02.Medium   
9231              Mumbai                   02.Medium   
9232              Mumbai                   02.Medium   
9233              Select                         NaN   
9234              Mumbai                   02.Medium   
9235              Mumbai                   02.Medium   
9236              Mumbai                   02.Medium   
9237              Mumbai                   02.Medium   
9238  Other Metro Cities                   02.Medium   
9239        Other Cities                   02.Medium   

     Asymmetrique Profile Index Asymmetrique Activity Score  \
9230                    01.High                        13.0   
9231                    01.High                        15.0   
9232                    01.High                        14.0   
9233                        NaN                         NaN   
9234                    01.High                        14.0   
9235                    01.High                    

In [326]:
# Mostrar estrutura do DataFrame
df_leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   Prospect ID                                    9240 non-null   object 
 1   Lead Number                                    9240 non-null   int64  
 2   Lead Origin                                    9240 non-null   object 
 3   Lead Source                                    9204 non-null   object 
 4   Do Not Email                                   9240 non-null   object 
 5   Do Not Call                                    9240 non-null   object 
 6   Converted                                      9240 non-null   int64  
 7   TotalVisits                                    9103 non-null   float64
 8   Total Time Spent on Website                    9240 non-null   int64  
 9   Page Views Per Visit                           9103 

### Featuring Engineering e Data Cleaning

In [327]:
# Remover as colunas Prospect ID e Lead Number
df_leads.drop(columns=['Prospect ID', 'Lead Number'], axis=1, inplace=True)

In [328]:
# Mostrar e remover as colunas categóricas que possuem somante um valor possível
for column in df_leads.select_dtypes(include=['object']).columns:
    if df_leads[column].nunique() == 1:
        print(f'Coluna {column} possui somente um valor possível: {df_leads[column].unique()}')
        df_leads.drop(columns=[column], axis=1, inplace=True)

Coluna Magazine possui somente um valor possível: ['No']
Coluna Receive More Updates About Our Courses possui somente um valor possível: ['No']
Coluna Update me on Supply Chain Content possui somente um valor possível: ['No']
Coluna Get updates on DM Content possui somente um valor possível: ['No']
Coluna I agree to pay the amount through cheque possui somente um valor possível: ['No']


In [329]:
# Mostrar os valores possíveis para todas as colunas categóricas
for column in df_leads.select_dtypes(include=['object']).columns:
    print(f'Coluna: {column} Valores possíveis: {df_leads[column].unique()}')


Coluna: Lead Origin Valores possíveis: ['API' 'Landing Page Submission' 'Lead Add Form' 'Lead Import'
 'Quick Add Form']
Coluna: Lead Source Valores possíveis: ['Olark Chat' 'Organic Search' 'Direct Traffic' 'Google' 'Referral Sites'
 'Welingak Website' 'Reference' 'google' 'Facebook' nan 'blog'
 'Pay per Click Ads' 'bing' 'Social Media' 'WeLearn' 'Click2call'
 'Live Chat' 'welearnblog_Home' 'youtubechannel' 'testone' 'Press_Release'
 'NC_EDM']
Coluna: Do Not Email Valores possíveis: ['No' 'Yes']
Coluna: Do Not Call Valores possíveis: ['No' 'Yes']
Coluna: Last Activity Valores possíveis: ['Page Visited on Website' 'Email Opened' 'Unreachable'
 'Converted to Lead' 'Olark Chat Conversation' 'Email Bounced'
 'Email Link Clicked' 'Form Submitted on Website' 'Unsubscribed'
 'Had a Phone Conversation' 'View in browser link Clicked' nan
 'Approached upfront' 'SMS Sent' 'Visited Booth in Tradeshow'
 'Resubscribed to emails' 'Email Received' 'Email Marked Spam']
Coluna: Country Valores possívei

In [330]:
# Mostrar o percentual de valores ausentes ou com valor igual a 'Select' para cada coluna categórica
for column in df_leads.select_dtypes(include=['object']).columns:
    contagem_nulas = (df_leads[column] == 'Select').sum() + df_leads[column].isnull().sum()
    print(f'{column}: {contagem_nulas / len(df_leads) * 100:.2f}%')

Lead Origin: 0.00%
Lead Source: 0.39%
Do Not Email: 0.00%
Do Not Call: 0.00%
Last Activity: 1.11%
Country: 26.63%
Specialization: 36.58%
How did you hear about X Education: 78.46%
What is your current occupation: 29.11%
What matters most to you in choosing a course: 29.32%
Search: 0.00%
Newspaper Article: 0.00%
X Education Forums: 0.00%
Newspaper: 0.00%
Digital Advertisement: 0.00%
Through Recommendations: 0.00%
Tags: 36.29%
Lead Quality: 51.59%
Lead Profile: 74.19%
City: 39.71%
Asymmetrique Activity Index: 45.65%
Asymmetrique Profile Index: 45.65%
A free copy of Mastering The Interview: 0.00%
Last Notable Activity: 0.00%


In [331]:
# Remover colunas categóricas cujo percentual de valores ausentes ou com valor igual a 'Select' maior que 25%
for column in df_leads.select_dtypes(include=['object']).columns:
    contagem_nulas = (df_leads[column] == 'Select').sum() + df_leads[column].isnull().sum()
    if (contagem_nulas / len(df_leads) * 100) > 25:
        print(f'{column}: {contagem_nulas / len(df_leads) * 100:.2f}%')
        df_leads.drop(columns=[column], axis=1, inplace=True)
        

Country: 26.63%
Specialization: 36.58%
How did you hear about X Education: 78.46%
What is your current occupation: 29.11%
What matters most to you in choosing a course: 29.32%
Tags: 36.29%
Lead Quality: 51.59%
Lead Profile: 74.19%
City: 39.71%
Asymmetrique Activity Index: 45.65%
Asymmetrique Profile Index: 45.65%


In [332]:
# Na coluna Lead Source, substituir o valor 'google' por 'Google'
df_leads['Lead Source'] = df_leads['Lead Source'].apply(lambda x: 'Google' if x == 'google' else x)

In [333]:
# Converter valores de colunas categóricas de Yes/No para 1/0
for column in df_leads.select_dtypes(include=['object']).columns:
    valores_unicos = df_leads[column].unique()
    if set(valores_unicos).issubset(set(['Yes', 'No'])):
        print(f'{column}')
        df_leads[column] = df_leads[column].apply(lambda x: 1 if x == 'Yes' else 0)

Do Not Email
Do Not Call
Search
Newspaper Article
X Education Forums
Newspaper
Digital Advertisement
Through Recommendations
A free copy of Mastering The Interview


In [334]:
# Remover linhas com valores ausentes em colunas categóricas
colunas_categoricas = df_leads.select_dtypes(include=['object']).columns
df_leads.dropna(subset=colunas_categoricas, inplace=True)

In [335]:
# Apresentar Estatísticas Descritivas
df_leads.describe()

Do Not Email  Do Not Call    Converted  TotalVisits  \
count   9103.000000  9103.000000  9103.000000  9074.000000   
mean       0.079205     0.000220     0.379216     3.456028   
std        0.270073     0.014822     0.485219     4.858802   
min        0.000000     0.000000     0.000000     0.000000   
25%        0.000000     0.000000     0.000000     1.000000   
50%        0.000000     0.000000     0.000000     3.000000   
75%        0.000000     0.000000     1.000000     5.000000   
max        1.000000     1.000000     1.000000   251.000000   

       Total Time Spent on Website  Page Views Per Visit       Search  \
count                  9103.000000           9074.000000  9103.000000   
mean                    483.773921              2.370151     0.001538   
std                     545.519186              2.160871     0.039189   
min                       0.000000              0.000000     0.000000   
25%                      12.000000              1.000000     0.000000   
50%                     247.000000              2.000000     0.000000   
75%                     924.000000              3.200000     0.000000   
max                    2272.000000             55.000000     1.000000   

       Newspaper Article  X Education Forums    Newspaper  \
count        9103.000000         9103.000000  9103.000000   
mean            0.000220            0.000110     0.000110   
std             0.014822            0.010481     0.010481   
min             0.000000            0.000000     0.000000   
25%             0.000000            0.000000     0.000000   
50%             0.000000            0.000000     0.000000   
75%             0.000000            0.000000     0.000000   
max             1.000000            1.000000     1.000000   

       Digital Advertisement  Through Recommendations  \
count            9103.000000              9103.000000   
mean                0.000439                 0.000769   
std                 0.020959                 0.027721   
min                 0.000000                 0.000000   
25%                 0.000000                 0.000000   
50%                 0.000000                 0.000000   
75%                 0.000000                 0.000000   
max                 1.000000                 1.000000   

       Asymmetrique Activity Score  Asymmetrique Profile Score  \
count                  4944.000000                 4944.000000   
mean                     14.313511                   16.340210   
std                       1.394627                    1.807428   
min                       7.000000                   11.000000   
25%                      14.000000                   15.000000   
50%                      14.000000                   16.000000   
75%                      15.000000                   18.000000   
max                      18.000000                   20.000000   

       A free copy of Mastering The Interview  
count                             9103.000000  
mean                                 0.317258  
std                                  0.465434  
min                                  0.000000  
25%                                  0.000000  
50%                                  0.000000  
75%                                  1.000000  
max                                  1.000000

In [336]:
# Mostrar e remover as colunas numéricas que possuem somante um valor possível
for column in df_leads.select_dtypes(include=['number']).columns:
    if df_leads[column].nunique() == 1:
        print(f'Coluna {column} possui somente um valor possível: {df_leads[column].unique()}')
        df_leads.drop(columns=[column], axis=1, inplace=True)

In [337]:
# Mostrar o percentual de valores ausentes para cada coluna numérica
for column in df_leads.select_dtypes(include=['number']).columns:
    contagem_nulas = (df_leads[column] == 'Select').sum() + df_leads[column].isnull().sum()
    print(f'{column}: {contagem_nulas / len(df_leads) * 100:.2f}%')

Do Not Email: 0.00%
Do Not Call: 0.00%
Converted: 0.00%
TotalVisits: 0.32%
Total Time Spent on Website: 0.00%
Page Views Per Visit: 0.32%
Search: 0.00%
Newspaper Article: 0.00%
X Education Forums: 0.00%
Newspaper: 0.00%
Digital Advertisement: 0.00%
Through Recommendations: 0.00%
Asymmetrique Activity Score: 45.69%
Asymmetrique Profile Score: 45.69%
A free copy of Mastering The Interview: 0.00%


In [338]:
# Remover colunas numéricas cujo percentual de valores ausentes sejam maior que 25%
for column in df_leads.select_dtypes(include=['number']).columns:
    contagem_nulas = df_leads[column].isnull().sum()
    if (contagem_nulas / len(df_leads) * 100) > 25:
        print(f'{column}: {contagem_nulas / len(df_leads) * 100:.2f}%')
        df_leads.drop(columns=[column], axis=1, inplace=True)

Asymmetrique Activity Score: 45.69%
Asymmetrique Profile Score: 45.69%


In [339]:
# Remover linhas com valores ausentes em colunas numéricas
colunas_numericas = df_leads.select_dtypes(include=['number']).columns
df_leads.dropna(subset=colunas_numericas, inplace=True)

### EDA

Hit Ratio
- Razão entre leads convertidos em vendas sobre quantidade total de leads (Conceito 1)
100 leads criados e 30 foram convertidos = 30%
- Razão entre leads convertidos em vendas sobre quantidade de leads encerrados (Conceito 2)
100 leads criados, 20 leads que não foram convertidos e 20 leads que foram convertidos = 50%

In [340]:
# Distribuição da variável target em percentual

fig = px.bar(
    df_leads['Converted'].value_counts() / len(df_leads) * 100,
    title='Hit Ratio - Fator de Conversão',
    labels={'index': 'Converted', 'value': 'Percentual'},
    opacity=0.8
)

fig.update_layout(showlegend=False)
fig.show()

In [341]:
# Matriz de Correlação das variáveis numéricas com Plotly Go
corr_matrix = df_leads.select_dtypes(include=['number']).corr()

In [342]:
# plot de Correlação
fig = go.Figure()

fig.add_trace(
    go.Heatmap(
        x = corr_matrix.columns,
        y = corr_matrix.index,
        z = np.array(corr_matrix),
        text = corr_matrix.values,
        texttemplate='%{text:.2f}',
        colorscale=px.colors.diverging.RdBu,
        zmin=-1,
        zmax=1,
    )
)

fig.show()

In [343]:
# BoxPlot Converted x TotalVisits
fig = px.box(df_leads, x='Converted', y='TotalVisits', color='Converted')
fig.show()

In [344]:
# BoxPlot Converted x Total Time Spent on Website
fig = px.box(df_leads, x='Converted', y='Total Time Spent on Website', color='Converted')
fig.show()

In [345]:
# BoxPlot Converted x Page Views Per Visit
fig = px.box(df_leads, x='Converted', y='Page Views Per Visit', color='Converted')
fig.show()

In [346]:
# Criar uma tabela da contingência de Converted x Lead Source
contingency_table_lead_source = pd.crosstab(df_leads['Converted'], df_leads['Lead Source'])

In [347]:
# Mostrar a tabela de contingência
contingency_table_lead_source

Lead Source  Click2call  Direct Traffic  Facebook  Google  Live Chat  NC_EDM  \
Converted                                                                      
0                     1            1725        22    1726          0       0   
1                     3             818         9    1147          2       1   

Lead Source  Olark Chat  Organic Search  Pay per Click Ads  Press_Release  \
Converted                                                                   
0                  1305             718                  1              2   
1                   448             436                  0              0   

Lead Source  Reference  Referral Sites  Social Media  WeLearn  \
Converted                                                       
0                   33              94             1        0   
1                  410              31             1        1   

Lead Source  Welingak Website  bing  blog  testone  welearnblog_Home  \
Converted                                                              
0                           2     5     1        1                 1   
1                         127     1     0        0                 0   

Lead Source  youtubechannel  
Converted                    
0                         1  
1                         0

In [348]:
# Executar o teste de independência de qui_quadrado
chi2, p_value, dof, expected = chi2_contingency(contingency_table_lead_source)

# Mostrar o resultado
print(f'Estatística qui-quadrado: {chi2}')
print(f'Valor p: {p_value}')
print(f'Graus de Liberdade: {dof}')
print(f'Existe uma relação significativa entre Converted e Lead Source: {p_value < 0.05}')

Estatística qui-quadrado: 942.1372507753774
Valor p: 1.1748671316223743e-187
Graus de Liberdade: 19
Existe uma relação significativa entre Converted e Lead Source: True


In [349]:
# Criar uma tabela de contingência de Converted x Lead Origin
contingency_table_lead_origin = pd.crosstab(df_leads['Converted'], df_leads['Lead Origin'])

In [350]:
# Mostrar a tabelo de contingência
contingency_table_lead_origin

Lead Origin   API  Landing Page Submission  Lead Add Form  Lead Import
Converted                                                             
0            2463                     3118             37           21
1            1115                     1767            544            9

In [351]:
# Executar o teste de independência d qui_quadrado
chi2, p_value, dof, expected = chi2_contingency(contingency_table_lead_origin)

# Mostrar o resultado
print(f'Estatística qui-quadrado: {chi2}')
print(f'Valor p: {p_value}')
print(f'Graus de Liberdade: {dof}')
print(f'Existe uma relação significativa entre Converted e Origin: {p_value < 0.05}')

Estatística qui-quadrado: 843.1212236836468
Valor p: 1.9228780932726904e-182
Graus de Liberdade: 3
Existe uma relação significativa entre Converted e Origin: True


In [352]:
# Criar uma tabela da contingência de Converted x Last Notable Activity
contingency_table_lead_lna = pd.crosstab(df_leads['Converted'], df_leads['Last Notable Activity'])

In [353]:
# Mostrar tabela
contingency_table_lead_lna

Last Notable Activity  Approached upfront  Email Bounced  Email Link Clicked  \
Converted                                                                      
0                                       0             51                 128   
1                                       1              9                  45   

Last Notable Activity  Email Marked Spam  Email Opened  Email Received  \
Converted                                                                
0                                      0          1781               0   
1                                      2          1042               1   

Last Notable Activity  Form Submitted on Website  Had a Phone Conversation  \
Converted                                                                    
0                                              1                         1   
1                                              0                        13   

Last Notable Activity  Modified  Olark Chat Conversation  \
Converted                                                  
0                          2587                      158   
1                           680                       25   

Last Notable Activity  Page Visited on Website  Resubscribed to emails  \
Converted                                                                
0                                          225                       0   
1                                           93                       1   

Last Notable Activity  SMS Sent  Unreachable  Unsubscribed  \
Converted                                                    
0                           663           10            33   
1                          1489           22            12   

Last Notable Activity  View in browser link Clicked  
Converted                                            
0                                                 1  
1                                                 0

In [354]:
# Executar o teste de independência d qui_quadrado
chi2, p_value, dof, expected = chi2_contingency(contingency_table_lead_lna)

# Mostrar o resultado
print(f'Estatística qui-quadrado: {chi2}')
print(f'Valor p: {p_value}')
print(f'Graus de Liberdade: {dof}')
print(f'Existe uma relação significativa entre Converted e Last notable Activity: {p_value < 0.05}')

Estatística qui-quadrado: 1424.6171966295433
Valor p: 8.365508263958168e-295
Graus de Liberdade: 15
Existe uma relação significativa entre Converted e Last notable Activity: True


### Preparação dos dados

In [355]:
# Preparar os dados para o modelo
X = df_leads.drop(columns=['Converted'])
y = df_leads['Converted']

In [356]:
# Criar Column Transformer para Normalizar Numérica e One-Hot Encoding
numeric_features = X.select_dtypes(include=['number']).columns
categorical_features = X.select_dtypes(include=['object']).columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
    ]
)

In [357]:
# Dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

# Aplicar Column Transformer
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [358]:
# Mostrar os conjuntos
print(X_train.shape)
print(X_test.shape)

(7259, 68)
(1815, 68)


### Treinamento do Modelo

In [ ]:
# Criar o modelo de BaggingClassifier
bagging_model = BaggingClassifier(
    estimator = LogisticRegression(),
    n_estimators = 10,
    random_state = 51,
    max_samples=0.3,
    # max_features=0.3,
)

In [378]:
# Treinar o modelo
bagging_model.fit(X_train, y_train)

BaggingClassifier(estimator=LogisticRegression(), max_features=0.3,
                  max_samples=0.3, random_state=51)

### Avaliação do Modelo

In [379]:
# Fazer predições no conjunto de testes
y_pred = bagging_model.predict(X_test)

In [380]:
# Avaliar o modelo
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [381]:
# Mostrar resultados
print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')
print(f'Recall: {recall}')
print(f'F1-Score: {f1}')

Acurácia: 0.7509641873278237
Precisão: 0.7422222222222222
Recall: 0.49850746268656715
F1-Score: 0.5964285714285714


In [364]:
# Mostrar uma matriz de confusão em Plotly
conf_matrix = confusion_matrix(y_test, y_pred)

fig = px.imshow(
    conf_matrix,
    labels=dict(x='Predição', y='Real', color='Contagem'),
    x=['Not Converted', 'Converted'],
    y=['Not Converted', 'Converted'],
    color_continuous_scale='Viridis'
)

fig.update_traces(text=conf_matrix, texttemplate="%{z}")
fig.update_layout(coloraxis_showscale=False)

fig.show()

In [365]:
# Calcular a importância das variáveis
importances = np.mean([np.abs(estimator.coef_[0]) for estimator in bagging_model.estimators_], axis=0)
len(importances)

68

In [366]:
# Obter os nomes das features após o preprocessor
feature_names = (numeric_features.tolist() + preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features).tolist())
len(feature_names)

68

In [367]:
# Criar um Dataframe combinando nomes das features e as importâncias
df_feature_importances = pd.DataFrame({'Feature': feature_names, 'Importance': importances})

In [368]:
# Ordenar o Dataframe pela importância
df_feature_importances = df_feature_importances.sort_values(by='Importance', ascending=True)

In [369]:
# Plotar a importância das features
fig = px.bar(
    df_feature_importances, 
    x='Importance', 
    y='Feature',
    orientation='h', 
    title='Importância das features (com base nos coeficientes absolutos)'
)

fig.update_layout(height=1280, width=1000, yaxis={'categoryorder': 'total ascending'})
fig.show()

### Some more things

In [385]:
bagging_model.estimators_samples_

[array([6406,  685, 6836, ..., 1652, 3092, 1535],
       shape=(2177,), dtype=int32),
 array([4792, 1818,  976, ..., 3085, 2558, 3027],
       shape=(2177,), dtype=int32),
 array([3886, 2327, 5553, ..., 6337, 1302, 5998],
       shape=(2177,), dtype=int32),
 array([6393, 6750, 2647, ..., 3684, 4862, 7077],
       shape=(2177,), dtype=int32),
 array([4484, 5292, 5462, ..., 3761, 5032, 5102],
       shape=(2177,), dtype=int32),
 array([3265, 1934, 1857, ..., 2656, 3488, 7207],
       shape=(2177,), dtype=int32),
 array([4257, 1116, 3993, ..., 5225, 5510, 4599],
       shape=(2177,), dtype=int32),
 array([6792, 1181,  504, ..., 2153, 5534, 3245],
       shape=(2177,), dtype=int32),
 array([ 746,  436, 4976, ...,  508, 2021,   33],
       shape=(2177,), dtype=int32),
 array([1008, 1458, 1182, ..., 2082, 4120, 1192],
       shape=(2177,), dtype=int32)]

In [386]:
bagging_model.estimators_samples_[4].shape

(2177,)

In [387]:
bagging_model.estimators_features_

[array([ 5, 12,  7,  2, 46, 40, 45,  9,  8, 56,  4, 54, 32, 63, 53, 34, 51,
        33, 59, 50], dtype=int32),
 array([13, 19, 63, 34, 43, 30, 67, 29, 55, 21,  7, 52, 47, 59, 14, 56, 66,
        57, 39, 27], dtype=int32),
 array([10,  3,  5, 52, 20, 41, 63, 17, 37,  2, 44, 45,  9, 32, 57, 48, 40,
        24, 25, 16], dtype=int32),
 array([11, 24, 51, 48,  6, 64, 34, 60, 45, 25, 63, 67, 17, 27, 14, 56, 57,
         5, 41, 43], dtype=int32),
 array([13, 19, 59, 62, 50,  4,  7, 23, 47, 64, 21,  9, 12, 29, 35, 52,  2,
        45, 28, 51], dtype=int32),
 array([58, 25, 46, 67, 20, 32, 36, 37, 64, 21, 39, 27, 11, 22,  1, 53,  7,
        24, 55, 66], dtype=int32),
 array([30, 56, 61, 19, 28, 43, 11, 18, 45, 46, 36, 16, 54,  3, 41, 17, 63,
        29, 12,  9], dtype=int32),
 array([25, 48, 37, 61, 30, 47, 29, 13, 46, 64, 43, 53, 17,  8, 32, 27, 63,
        18, 66, 24], dtype=int32),
 array([67, 47,  3,  2, 21, 52, 64, 55, 42,  0, 38, 33,  5, 41, 10,  6,  1,
        35, 62,  4], dtype=int32),
 

In [388]:
# Predizer probabilidade de Conversão
y_pred_prob = bagging_model.predict_proba(X_test)

In [389]:
y_pred_prob

array([[0.40769847, 0.59230153],
       [0.74805414, 0.25194586],
       [0.74805414, 0.25194586],
       ...,
       [0.78117086, 0.21882914],
       [0.81479581, 0.18520419],
       [0.27125281, 0.72874719]], shape=(1815, 2))

### Cenário de CRM - Utilizando da Probabilidade

- CRM
    Leads concluídos -Resultado Positivo ou Negativo
    Leads em aberto - Não tenho Resultado

Treine um modelo no que está concluído, para que ele generalize bem no está em aberto

- Lead em aberto:
    + Probabilidade de Converter:
        Quando muito alto, podemos olhar com mais foco pra realmente converter

    + Quando muito baixo, podemos meio que descartar importância das Features
    
    

In [375]:
# Salvar Dataframe como CSV
df_leads.to_csv('./datasets/leads_cleaned.csv', index=False)

In [376]:
# Salvar o preprocessor
import joblib

joblib.dump(preprocessor, './preprocessor_dataset_leads.pkl')

['./preprocessor_dataset_leads.pkl']